name: workflow_1
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Install dependencies 
        run: npm install
      - name: run tests
        run:  npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Install dependencies 
        run: npm install
      - name: run lint
        run: npm run lint
  build:
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: run build
        run: echo "Build step completed successfully"