name: workflow_2

on:
    push:
        branches:
            - main
            - dev
env:
    APP_NAME: ${{ vars.APP_NAME}}
    APP_VERSION: ${{ vars.APP_VERSION}}
    DB_NAME: ${{ secrets.DB_NAME}}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
    DB_PORT: ${{ secrets.DB_PORT}}
jobs:
    tests:
        runs-on: ubuntu-24.04
        outputs: 
            MI_OUTPUT: ${{ steps.MI_OUTPUT.outputs.nombre_random }}
        steps:
            - name: OBTENER_CODIGO
              uses: actions/checkout@v7
            - name: INSTALAR_NODE
              uses: actions/setup-node@v7
              with:
                node-version: '24'
                cache: 'npm'
            - name: OUTPUT_SETUP
              id: MI_OUTPUT
              run: echo "nombre_random=ESTO ES UNA PRUENBA" >> "$GITHUB_OUTPUT"
            - name: INSTALAR_DEPENDENCIAS
              run: npm ci
            - name: EJECUTAR TESTS
              run: npm test
    lint:
        runs-on: ubuntu-24.04
        steps:
            - name: OBTENER_CODIGO
              uses: actions/checkout@v7
            - name: INSTALAR_NODE
              uses: actions/setup-node@v7
              with:
                node-version: '24'
                cache: 'npm'
            - name: INSTALAR_DEPENDENCIAS
              run: npm ci
            - name: EJECUTAR LINTER
              run: npm run lint
    deploy:
        needs: [lint,tests]
        runs-on: ubuntu-24.04
        steps:
            - name: OBTENER_CODIGO
              uses: actions/checkout@v7
            - name: INSTALAR_NODE
              uses: actions/setup-node@v7
              with:
                node-version: '24'
                cache: 'npm'
            - name: USANDO_OUTPUT
              run: echo "${{ needs.tests.outputs.MI_OUTPUT }}"
            - name: INSTALAR_DEPENDENCIAS
              run: npm ci
            - name: VALIDAR_APP
              run: | 
                echo "
                Repository: ${{ github.repository }}
                sha: ${{github.sha }}
                Branch: ${{ github.ref_name }}
                Actor: ${{github.actor }} 
                Application: ${{vars.APP_NAME}} -  ${{vars.APP_VERSION}}
                Database Password Exists ✔"
            - name: COMPILAR_APP
              run: npm run build
            - name: SUBIR_ARTEFACTO
              uses: actions/upload-artifact@v7
              with:
                name: dist-build
                path: dist
                if-no-files-found: error 


        